import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE / "_core"))
from domain import unpack, check_profile
from intrinsic import feature_row
from structural import knapsack_relation_features
from runtime import run_cli

SPEC = {'problem': 'KP',
 'name': '背包问题',
 'kind': 'knapsack',
 'fields': {'weights': {'type': 'vector', 'aliases': ['weights', 'weight', 'costs', 'cost']},
            'profit': {'type': 'vector',
                       'aliases': ['values', 'value', 'profits', 'profit', 'benefits', 'returns']},
            'capacity': {'type': 'scalar',
                         'aliases': ['capacity', 'budget', 'budget_limit', 'total_budget']}},
 'primary_variant': 'domain',
 'candidate_features': ['weights_count',
                        'weights_mean',
                        'weights_var',
                        'weights_std',
                        'weights_min',
                        'weights_max',
                        'weights_q25',
                        'weights_median',
                        'weights_q75',
                        'weights_zero_ratio',
                        'weights_negative_ratio',
                        'weights_unique_ratio',
                        'weights_cv',
                        'weights_skew',
                        'weights_kurtosis',
                        'profit_count',
                        'profit_mean',
                        'profit_var',
                        'profit_std',
                        'profit_min',
                        'profit_max',
                        'profit_q25',
                        'profit_median',
                        'profit_q75',
                        'profit_zero_ratio',
                        'profit_negative_ratio',
                        'profit_unique_ratio',
                        'profit_cv',
                        'profit_skew',
                        'profit_kurtosis',
                        'capacity_count',
                        'capacity_mean',
                        'capacity_var',
                        'capacity_std',
                        'capacity_min',
                        'capacity_max',
                        'capacity_q25',
                        'capacity_median',
                        'capacity_q75',
                        'capacity_zero_ratio',
                        'capacity_negative_ratio',
                        'capacity_unique_ratio',
                        'capacity_cv',
                        'capacity_skew',
                        'capacity_kurtosis',
                        'capacity_total_weight_ratio',
                        'profit_weight_ratio_count',
                        'profit_weight_ratio_mean',
                        'profit_weight_ratio_var',
                        'profit_weight_ratio_std',
                        'profit_weight_ratio_min',
                        'profit_weight_ratio_max',
                        'profit_weight_ratio_q25',
                        'profit_weight_ratio_median',
                        'profit_weight_ratio_q75',
                        'profit_weight_ratio_zero_ratio',
                        'profit_weight_ratio_negative_ratio',
                        'profit_weight_ratio_unique_ratio',
                        'profit_weight_ratio_cv',
                        'profit_weight_ratio_skew',
                        'profit_weight_ratio_kurtosis',
                        'kp_relative_weight_q00',
                        'kp_relative_weight_q25',
                        'kp_relative_weight_q50',
                        'kp_relative_weight_q75',
                        'kp_relative_weight_q100',
                        'kp_relative_weight_mean',
                        'kp_relative_weight_std',
                        'kp_relative_value_density_q00',
                        'kp_relative_value_density_q25',
                        'kp_relative_value_density_q50',
                        'kp_relative_value_density_q75',
                        'kp_relative_value_density_q100',
                        'kp_relative_value_density_mean',
                        'kp_relative_value_density_std',
                        'kp_pair_slack_q00',
                        'kp_pair_slack_q25',
                        'kp_pair_slack_q50',
                        'kp_pair_slack_q75',
                        'kp_pair_slack_q100',
                        'kp_pair_slack_mean',
                        'kp_pair_slack_std',
                        'kp_partner_fraction_q00',
                        'kp_partner_fraction_q25',
                        'kp_partner_fraction_q50',
                        'kp_partner_fraction_q75',
                        'kp_partner_fraction_q100',
                        'kp_partner_fraction_mean',
                        'kp_partner_fraction_std',
                        'kp_weight_gini',
                        'kp_profit_gini',
                        'kp_weight_profit_pearson',
                        'kp_weight_profit_spearman',
                        'kp_weight_profit_correlation_undefined',
                        'kp_pair_fit_ratio',
                        'kp_pair_exact_fit_ratio',
                        'kp_pair_lower_weight_higher_profit_ratio',
                        'kp_identical_item_pair_ratio',
                        'kp_oversize_item_ratio',
                        'kp_zero_profit_item_ratio'],
 'default_features': None,
 'latest_measurement': True,
 'latest_analysis': True}


def calculate_features(parameters, question=None):
    data = unpack(parameters)
    variant = SPEC["primary_variant"]
    check_profile(SPEC, data)
    result = feature_row(SPEC, variant, data)
    result.update(knapsack_relation_features(data))
    return result


if __name__ == "__main__":
    run_cli(SPEC, calculate_features)
